//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectdotNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COFFEESTOREEntities : DbContext
    {
        public COFFEESTOREEntities()
            : base("name=COFFEESTOREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblACCOUNT> tblACCOUNT { get; set; }
        public virtual DbSet<tblBILL> tblBILL { get; set; }
        public virtual DbSet<tblBILL_INFO> tblBILL_INFO { get; set; }
        public virtual DbSet<tblCATEGORY> tblCATEGORY { get; set; }
        public virtual DbSet<tblEMPLOYEE> tblEMPLOYEE { get; set; }
        public virtual DbSet<tblPRODUCT> tblPRODUCT { get; set; }
        public virtual DbSet<tblTABLE> tblTABLE { get; set; }
    }
}
